export interface TriviaQuestion {
  id: string;
  question: string;
  category: string;
  categoryEmoji: string;
  options?: string[]; // Si no tiene opciones, es pregunta abierta directa
  correctAnswer: string;
  hint?: string;
}

export const OFFICIAL_TRIVIA_QUESTIONS: TriviaQuestion[] = [
  // 🎬 SERIES, CINE Y NOSTALGIA 2000s
  {
    id: 'triv_1',
    category: 'Series & Televisión',
    categoryEmoji: '📺',
    question: 'En "Aquí No Hay Quien Viva", ¿cómo se llamaba el perro de Vicenta y Doña Concha?',
    options: ['Valentín', 'Ramiro', 'Toby', 'Curro'],
    correctAnswer: 'Valentín',
    hint: 'Siempre le daban croquetas y le tenían un cariño enfermizo',
  },
  {
    id: 'triv_2',
    category: 'Series & Televisión',
    categoryEmoji: '📺',
    question: '¿Qué mítica serie española de los 2000 terminaba revelando que todas sus 8 temporadas habían sido un sueño de Resines?',
    options: ['Los Serrano', 'Médico de Familia', 'Periodistas', 'Compañeros'],
    correctAnswer: 'Los Serrano',
    hint: 'Diego Serrano se despertaba en la cama al lado de Lucía',
  },
  {
    id: 'triv_3',
    category: 'Series & Televisión',
    categoryEmoji: '📺',
    question: 'En "Friends", ¿cuál era el trabajo exacto de Chandler Bing del que ninguno de sus amigos se acordaba?',
    options: ['Análisis estadístico y reconfiguración de datos', 'Contable fiscal', 'Publicista creativo', 'Consultor financiero'],
    correctAnswer: 'Análisis estadístico y reconfiguración de datos (¡Transpondedor no existe!)',
    hint: 'Rachel y Monica perdieron el piso por decir que era "Transpondedor"',
  },
  {
    id: 'triv_4',
    category: 'Series & Televisión',
    categoryEmoji: '📺',
    question: '¿En qué pueblo ficticio de Indiana está ambientada la serie "Stranger Things"?',
    options: ['Hawkins', 'Riverdale', 'Twin Peaks', 'Sunnydale'],
    correctAnswer: 'Hawkins',
    hint: 'Donde está el laboratorio nacional y el "Upside Down"',
  },
  {
    id: 'triv_5',
    category: 'Series & Cine',
    categoryEmoji: '🎬',
    question: 'En "Shrek 2", ¿qué canción legendaria canta el Hada Madrina con piano mientras Shrek asalta el castillo a lomos de Mongo?',
    correctAnswer: 'Holding Out for a Hero (Yo quiero un héroe)',
    hint: 'Originalmente de Bonnie Tyler: "Where have all the good men gone..."',
  },
  {
    id: 'triv_6',
    category: 'Series & Televisión',
    categoryEmoji: '📺',
    question: 'En "Juego de Tronos", ¿cuál es el lema oficial de la Casa Stark de Invernalia?',
    correctAnswer: 'Winter is Coming (Se acerca el invierno)',
    hint: 'La frase más repetida de Ned Stark en toda la primera temporada',
  },
  {
    id: 'triv_7',
    category: 'Cine & Pop',
    categoryEmoji: '🎬',
    question: 'En la saga Harry Potter, ¿cuál es el hechizo utilizado para ahuyentar a los Dementores?',
    options: ['Expecto Patronum', 'Expelliarmus', 'Avada Kedavra', 'Lumos Maxima'],
    correctAnswer: 'Expecto Patronum',
    hint: 'El de Harry toma la forma corpórea de un ciervo',
  },
  {
    id: 'triv_8',
    category: 'Cine & Pop',
    categoryEmoji: '🎬',
    question: '¿Qué actor interpretó al Joker en la película "El Caballero Oscuro" (2008) de Nolan, ganando un Óscar póstumo?',
    correctAnswer: 'Heath Ledger',
    hint: 'Dejó la frase mítica: "Why so serious?"',
  },

  // 🎵 MÚSICA URBANA, POP Y FESTIVALES
  {
    id: 'triv_9',
    category: 'Música & Fiesta',
    categoryEmoji: '🔥',
    question: '¿Con qué artista canario grabó Bizarrap su histórica BZRP Music Sessions #52 ("Quédate")?',
    options: ['Quevedo', 'Cruz Cafuné', 'Saiko', 'Bejo'],
    correctAnswer: 'Quevedo',
    hint: '"Y nos fuimo\' en una, empezamo\' a la una..."',
  },
  {
    id: 'triv_10',
    category: 'Música & Fiesta',
    categoryEmoji: '🔥',
    question: '¿Cuál es el verdadero nombre de pila del cantante puertorriqueño Bad Bunny?',
    options: ['Benito Antonio Martínez Ocasio', 'Juan Carlos Ozuna', 'José Álvaro Osorio', 'Emmanuel Gazmey'],
    correctAnswer: 'Benito Antonio Martínez Ocasio',
    hint: 'Siempre empieza sus canciones diciendo "Benito"',
  },
  {
    id: 'triv_11',
    category: 'Música & Fiesta',
    categoryEmoji: '🔥',
    question: '¿Con qué álbum conceptual basado en la novela "Flamenca" saltó Rosalía a la fama mundial en 2018?',
    options: ['El Mal Querer', 'Motomami', 'Los Ángeles', 'Lux Æterna'],
    correctAnswer: 'El Mal Querer',
    hint: 'Incluía himnos como "Malamente" y "Pienso en tu mirá"',
  },
  {
    id: 'triv_12',
    category: 'Música & Fiesta',
    categoryEmoji: '🔥',
    question: '¿Qué alias o nombre artístico utilizaba C. Tangana en sus inicios en el rap madrileño antes de formar Agorazein?',
    options: ['Crema', 'Pucho', 'El Madrileño', 'Antón'],
    correctAnswer: 'Crema',
    hint: 'Su disco de 2008 se titulaba "Desde la octava ventana del bloque"',
  },
  {
    id: 'triv_13',
    category: 'Música & Fiesta',
    categoryEmoji: '🔥',
    question: '¿Qué canción mítica de Don Omar lanzada en 2010 tiene un estribillo en portugués que todo el mundo canta a gritos de fiesta?',
    correctAnswer: 'Danza Kuduro',
    hint: '"Oi, oi, oi, oi, vem para quebrar kuduro, vamos dançar kuduro..."',
  },
  {
    id: 'triv_14',
    category: 'Música & Pop',
    categoryEmoji: '🎸',
    question: '¿En qué año representó Chanel a España en Eurovisión con "SloMo", logrando un histórico 3.er puesto?',
    options: ['2022', '2021', '2023', '2020'],
    correctAnswer: '2022 (en Turín, Italia)',
    hint: 'El año del famosísimo "Chanelazo" y el dance break',
  },
  {
    id: 'triv_15',
    category: 'Música & Pop',
    categoryEmoji: '🎸',
    question: '¿Qué dos hermanos de Cornellà de Llobregat forman el dúo musical Estopa?',
    correctAnswer: 'David y José Muñoz',
    hint: 'Autores de "La raja de tu falda" y "Vino tinto"',
  },

  // 🎮 GAMING, REDES E INTERNET
  {
    id: 'triv_16',
    category: 'Gaming & Internet',
    categoryEmoji: '🎮',
    question: '¿Cuál es el videojuego más vendido de toda la historia, superando los 300 millones de copias?',
    options: ['Minecraft', 'Grand Theft Auto V', 'Tetris', 'Wii Sports'],
    correctAnswer: 'Minecraft',
    hint: 'Mundo abierto infinito de bloques creado originalmente por Notch',
  },
  {
    id: 'triv_17',
    category: 'Gaming & Internet',
    categoryEmoji: '🎮',
    question: 'En GTA San Andreas, ¿cuál es la célebre frase en inglés que dice CJ al volver a su barrio y ver a la policía corrupta?',
    correctAnswer: 'Ah shit, here we go again',
    hint: 'Uno de los memes más utilizados de la historia de internet',
  },
  {
    id: 'triv_18',
    category: 'Gaming & Internet',
    categoryEmoji: '🎮',
    question: '¿Cómo se llama el evento multitudinario de boxeo entre streamers y creadores organizado anualmente por Ibai Llanos?',
    options: ['La Velada del Año', 'King of the Ring', 'Streamer Fights', 'La Noche del Ring'],
    correctAnswer: 'La Velada del Año',
    hint: 'Ha llenado estadios como el Cívitas Metropolitano y el Santiago Bernabéu',
  },
  {
    id: 'triv_19',
    category: 'Gaming & Internet',
    categoryEmoji: '🎮',
    question: '¿Cuál de estos NO es un Pokémon inicial de la 1.ª generación de Kanto?',
    options: ['Totodile', 'Charmander', 'Squirtle', 'Bulbasaur'],
    correctAnswer: 'Totodile',
    hint: 'Totodile es el inicial de agua de la 2.ª generación (Johto)',
  },
  {
    id: 'triv_20',
    category: 'Gaming & Internet',
    categoryEmoji: '🎮',
    question: 'En el juego social "Among Us" que se viralizó durante la cuarentena de 2020, ¿cómo se llamaban los jugadores infiltrados que saboteaban la nave?',
    correctAnswer: 'Impostores',
    hint: '"There is 1 Impostor among us..."',
  },

  // 🍻 NOCHE, BAR & FIESTA
  {
    id: 'triv_21',
    category: 'Noche & Fiesta',
    categoryEmoji: '🍺',
    question: '¿De qué país centroeuropeo es originario el licor de hierbas Jägermeister?',
    options: ['Alemania', 'Austria', 'Suiza', 'Bélgica'],
    correctAnswer: 'Alemania',
    hint: 'Su logotipo es un ciervo con una cruz brillante entre sus cuernos',
  },
  {
    id: 'triv_22',
    category: 'Noche & Fiesta',
    categoryEmoji: '🍺',
    question: '¿Qué famosa marca andaluza de ginebra sevillana revolucionó las barras de fiesta en España por su color rosa y sabor a fresa?',
    correctAnswer: 'Puerto de Indias',
    hint: 'Se destila en Carmona (Sevilla)',
  },
  {
    id: 'triv_23',
    category: 'Noche & Fiesta',
    categoryEmoji: '🍺',
    question: 'En el chupito o cóctel "Jägerbomb", ¿qué bebida energética se mezcla habitualmente con el chorro de Jägermeister?',
    correctAnswer: 'Red Bull (o bebida energética con cafeína/taurina)',
    hint: 'Te da alas (y taquicardia)',
  },
  {
    id: 'triv_24',
    category: 'Noche & Fiesta',
    categoryEmoji: '🍺',
    question: '¿Cuál es la ciudad gallega en la que nació la fábrica de la cerveza Estrella Galicia?',
    options: ['A Coruña', 'Vigo', 'Santiago de Compostela', 'Ourense'],
    correctAnswer: 'A Coruña',
    hint: 'Fundada por José María Rivera Corral en 1906 en el barrio de Cuatro Caminos',
  },

  // ⚽ DEPORTE & GLORIA NACIONAL
  {
    id: 'triv_25',
    category: 'Deportes',
    categoryEmoji: '⚽',
    question: '¿En qué minuto exacto de la prórroga marcó Andrés Iniesta el gol que hizo a España campeona del mundo en Sudáfrica 2010?',
    options: ['Minuto 116', 'Minuto 110', 'Minuto 119', 'Minuto 105'],
    correctAnswer: 'Minuto 116',
    hint: 'Poco antes de los penaltis contra los Países Bajos',
  },
  {
    id: 'triv_26',
    category: 'Deportes',
    categoryEmoji: '⚽',
    question: '¿Cuántos Balones de Oro ha ganado Lionel Messi en toda su trayectoria deportiva profesional?',
    options: ['8', '7', '6', '9'],
    correctAnswer: '8 Balones de Oro',
    hint: 'El último conseguido tras el Mundial de Qatar 2022',
  },
  {
    id: 'triv_27',
    category: 'Deportes',
    categoryEmoji: '⚽',
    question: '¿Cuántas Copas de Europa / Champions League ha ganado el Real Madrid de fútbol masculino hasta 2024?',
    options: ['15', '14', '13', '16'],
    correctAnswer: '15 Champions League',
    hint: 'La 15.ª la consiguieron en Wembley contra el Borussia Dortmund',
  },
  {
    id: 'triv_28',
    category: 'Deportes',
    categoryEmoji: '⚽',
    question: '¿Qué tenista español ostenta el récord absoluto de 14 trofeos de Roland Garros sobre tierra batida?',
    correctAnswer: 'Rafa Nadal',
    hint: 'De Manacor, con su mítico grito de "¡VAMOOOS!"',
  },

  // 🌍 CULTURA POP & CURIOSIDADES
  {
    id: 'triv_29',
    category: 'Cultura Pop & Memes',
    categoryEmoji: '📱',
    question: 'En el mítico programa "El Diario de Patricia", ¿qué famosa frase soltó una invitada al enterarse de un embarazo en directo?',
    options: ['"¿Pero qué me estás container?"', '"¡Me he quedado muerta!"', '"El hijo no es tuyo, es de tu padre"', '"Yo no he sido"'],
    correctAnswer: '"¿Pero qué me estás container?"',
    hint: 'Se convirtió en una de las frases más parodiadas de la televisión española',
  },
  {
    id: 'triv_30',
    category: 'Cultura Pop & Memes',
    categoryEmoji: '📱',
    question: '¿Cómo se llama la cafetería neoyorquina donde los seis protagonistas de "Friends" se reunían en el sofá naranja?',
    correctAnswer: 'Central Perk',
    hint: 'Donde servía cafés Gunther',
  },
];
