export interface UnDosTresChallenge {
  id: string;
  prompt: string;
  level: string;
  levelNumber: number;
  examples: string[];
  category: string;
}

export const OFFICIAL_UN_DOS_TRES_CHALLENGES: UnDosTresChallenge[] = [
  // ============================================================================
  // RONDA 1 — MUY FÁCIL
  // ============================================================================
  {
    id: 'udt_1',
    level: 'Muy Fácil',
    levelNumber: 1,
    category: 'Naturaleza & Animales',
    prompt: 'Di 3 animales',
    examples: ['Perro', 'Gato', 'León', 'Elefante', 'Caballo', 'Tigre', 'Delfín'],
  },
  {
    id: 'udt_2',
    level: 'Muy Fácil',
    levelNumber: 1,
    category: 'Básicos',
    prompt: 'Di 3 colores',
    examples: ['Rojo', 'Azul', 'Verde', 'Amarillo', 'Negro', 'Blanco', 'Naranja'],
  },
  {
    id: 'udt_3',
    level: 'Muy Fácil',
    levelNumber: 1,
    category: 'Alimentación',
    prompt: 'Di 3 frutas',
    examples: ['Manzana', 'Plátano', 'Naranja', 'Fresa', 'Pera', 'Uva', 'Sandía'],
  },
  {
    id: 'udt_4',
    level: 'Muy Fácil',
    levelNumber: 1,
    category: 'Geografía',
    prompt: 'Di 3 países',
    examples: ['España', 'Francia', 'Italia', 'Alemania', 'México', 'Argentina', 'Japón'],
  },
  {
    id: 'udt_5',
    level: 'Muy Fácil',
    levelNumber: 1,
    category: 'Deportes',
    prompt: 'Di 3 deportes',
    examples: ['Fútbol', 'Baloncesto', 'Tenis', 'Natación', 'Pádel', 'Ciclismo', 'Atletismo'],
  },
  {
    id: 'udt_6',
    level: 'Muy Fácil',
    levelNumber: 1,
    category: 'Bebidas',
    prompt: 'Di 3 bebidas',
    examples: ['Agua', 'Cerveza', 'Coca-Cola', 'Vino', 'Café', 'Zumo de naranja', 'Té'],
  },
  {
    id: 'udt_7',
    level: 'Muy Fácil',
    levelNumber: 1,
    category: 'Gastronomía',
    prompt: 'Di 3 comidas',
    examples: ['Pizza', 'Tortilla de patatas', 'Paella', 'Hamburguesa', 'Pasta', 'Lentejas'],
  },
  {
    id: 'udt_8',
    level: 'Muy Fácil',
    levelNumber: 1,
    category: 'Nombres',
    prompt: 'Di 3 nombres de chico',
    examples: ['Alejandro', 'Pablo', 'David', 'Carlos', 'Javier', 'Daniel', 'Marcos'],
  },
  {
    id: 'udt_9',
    level: 'Muy Fácil',
    levelNumber: 1,
    category: 'Nombres',
    prompt: 'Di 3 nombres de chica',
    examples: ['Lucía', 'María', 'Sara', 'Laura', 'Paula', 'Carmen', 'Elena'],
  },
  {
    id: 'udt_10',
    level: 'Muy Fácil',
    levelNumber: 1,
    category: 'Trabajo',
    prompt: 'Di 3 profesiones',
    examples: ['Médico', 'Profesor', 'Bombero', 'Policía', 'Abogado', 'Camarero', 'Ingeniero'],
  },

  // ============================================================================
  // RONDA 2 — MUY FÁCIL
  // ============================================================================
  {
    id: 'udt_11',
    level: 'Muy Fácil',
    levelNumber: 2,
    category: 'Moda & Ropa',
    prompt: 'Di 3 prendas de ropa',
    examples: ['Camiseta', 'Pantalón', 'Chaqueta', 'Calcetines', 'Sudadera', 'Falda'],
  },
  {
    id: 'udt_12',
    level: 'Muy Fácil',
    levelNumber: 2,
    category: 'Transporte',
    prompt: 'Di 3 vehículos',
    examples: ['Coche', 'Moto', 'Bicicleta', 'Autobús', 'Tren', 'Avión', 'Barco'],
  },
  {
    id: 'udt_13',
    level: 'Muy Fácil',
    levelNumber: 2,
    category: 'Motor',
    prompt: 'Di 3 marcas de coches',
    examples: ['Seat', 'Ford', 'Renault', 'Toyota', 'BMW', 'Audi', 'Mercedes'],
  },
  {
    id: 'udt_14',
    level: 'Muy Fácil',
    levelNumber: 2,
    category: 'Hogar',
    prompt: 'Di 3 cosas que hay en una casa',
    examples: ['Sofá', 'Cama', 'Mesa', 'Televisión', 'Puerta', 'Lámpara', 'Armario'],
  },
  {
    id: 'udt_15',
    level: 'Muy Fácil',
    levelNumber: 2,
    category: 'Cocina',
    prompt: 'Di 3 cosas que hay en una cocina',
    examples: ['Nevera', 'Sartén', 'Microondas', 'Cuchillo', 'Horno', 'Tenedor', 'Plato'],
  },
  {
    id: 'udt_16',
    level: 'Muy Fácil',
    levelNumber: 2,
    category: 'Hogar',
    prompt: 'Di 3 cosas que hay en un baño',
    examples: ['Cepillo de dientes', 'Toalla', 'Papel higiénico', 'Champú', 'Ducha', 'Jabón'],
  },
  {
    id: 'udt_17',
    level: 'Muy Fácil',
    levelNumber: 2,
    category: 'Día a Día',
    prompt: 'Di 3 cosas que llevas en una mochila',
    examples: ['Llaves', 'Cartera', 'Botella de agua', 'Cuaderno', 'Bolígrafo', 'Portátil', 'Cargador'],
  },
  {
    id: 'udt_18',
    level: 'Muy Fácil',
    levelNumber: 2,
    category: 'Compras',
    prompt: 'Di 3 cosas que puedes comprar en un supermercado',
    examples: ['Leche', 'Pan', 'Huevos', 'Arroz', 'Galletas', 'Aceite', 'Manzanas'],
  },
  {
    id: 'udt_19',
    level: 'Muy Fácil',
    levelNumber: 2,
    category: 'Mascotas',
    prompt: 'Di 3 animales domésticos',
    examples: ['Perro', 'Gato', 'Hámster', 'Pájaro / Canario', 'Pez', 'Conejo'],
  },
  {
    id: 'udt_20',
    level: 'Muy Fácil',
    levelNumber: 2,
    category: 'Naturaleza',
    prompt: 'Di 3 animales que pueden volar',
    examples: ['Águila', 'Paloma', 'Murciélago', 'Loro', 'Mosca', 'Abeja', 'Gaviota'],
  },

  // ============================================================================
  // RONDA 3 — FÁCIL
  // ============================================================================
  {
    id: 'udt_21',
    level: 'Fácil',
    levelNumber: 3,
    category: 'Colegio',
    prompt: 'Di 3 cosas que encuentras en un colegio',
    examples: ['Pizarra', 'Pupitre', 'Mochila', 'Libros', 'Profesor', 'Goma de borrar'],
  },
  {
    id: 'udt_22',
    level: 'Fácil',
    levelNumber: 3,
    category: 'Educación',
    prompt: 'Di 3 asignaturas',
    examples: ['Matemáticas', 'Lengua', 'Historia', 'Inglés', 'Educación Física', 'Ciencias'],
  },
  {
    id: 'udt_23',
    level: 'Fácil',
    levelNumber: 3,
    category: 'Ciudad',
    prompt: 'Di 3 cosas que encuentras en un parque',
    examples: ['Columpios', 'Bancos', 'Árboles', 'Tobogán', 'Fuentes', 'Césped', 'Farolas'],
  },
  {
    id: 'udt_24',
    level: 'Fácil',
    levelNumber: 3,
    category: 'Ciudad',
    prompt: 'Di 3 cosas que encuentras en una calle',
    examples: ['Semáforo', 'Paso de peatones', 'Farola', 'Coches', 'Papelera', 'Acera'],
  },
  {
    id: 'udt_25',
    level: 'Fácil',
    levelNumber: 3,
    category: 'Objetos',
    prompt: 'Di 3 cosas que tienen ruedas',
    examples: ['Coche', 'Bicicleta', 'Patinete', 'Maleta', 'Carro de la compra', 'Moto'],
  },
  {
    id: 'udt_26',
    level: 'Fácil',
    levelNumber: 3,
    category: 'Tecnología',
    prompt: 'Di 3 cosas que tienen pantalla',
    examples: ['Móvil', 'Televisión', 'Ordenador / Portátil', 'Tablet', 'Reloj inteligente', 'Cajero automático'],
  },
  {
    id: 'udt_27',
    level: 'Fácil',
    levelNumber: 3,
    category: 'Bebidas',
    prompt: 'Di 3 cosas que puedes beber',
    examples: ['Agua', 'Leche', 'Zumo', 'Cerveza', 'Refresco', 'Batido', 'Sopa'],
  },
  {
    id: 'udt_28',
    level: 'Fácil',
    levelNumber: 3,
    category: 'Comida',
    prompt: 'Di 3 cosas que puedes comer con las manos',
    examples: ['Pizza', 'Hamburguesa', 'Patatas fritas', 'Tacos', 'Sándwich', 'Croquetas'],
  },
  {
    id: 'udt_29',
    level: 'Fácil',
    levelNumber: 3,
    category: 'Regalos',
    prompt: 'Di 3 cosas que puedes regalar',
    examples: ['Libro', 'Perfume', 'Ropa', 'Flores', 'Reloj', 'Chocolates', 'Videojuego'],
  },
  {
    id: 'udt_30',
    level: 'Fácil',
    levelNumber: 3,
    category: 'Verano',
    prompt: 'Di 3 cosas que puedes llevar a la playa',
    examples: ['Toalla', 'Sombrilla', 'Crema solar', 'Bañador', 'Nevera portátil', 'Chanclas'],
  },

  // ============================================================================
  // RONDA 4 — FÁCIL
  // ============================================================================
  {
    id: 'udt_31',
    level: 'Fácil',
    levelNumber: 4,
    category: 'Rutina',
    prompt: 'Di 3 cosas que haces por la mañana',
    examples: ['Lavarse los dientes', 'Desayunar', 'Ducharse', 'Vestirse', 'Hacer la cama', 'Mirar el móvil'],
  },
  {
    id: 'udt_32',
    level: 'Fácil',
    levelNumber: 4,
    category: 'Rutina',
    prompt: 'Di 3 cosas que haces antes de dormir',
    examples: ['Poner la alarma', 'Mirar el móvil', 'Lavarse los dientes', 'Apagar la luz', 'Leer un libro'],
  },
  {
    id: 'udt_33',
    level: 'Fácil',
    levelNumber: 4,
    category: 'Verano',
    prompt: 'Di 3 cosas que haces en la playa',
    examples: ['Bañarse', 'Tomar el sol', 'Jugar a las palas', 'Hacer castillos de arena', 'Dormir la siesta'],
  },
  {
    id: 'udt_34',
    level: 'Fácil',
    levelNumber: 4,
    category: 'Ocio',
    prompt: 'Di 3 cosas que haces cuando estás aburrido',
    examples: ['Mirar TikTok / Instagram', 'Abrir la nevera', 'Ver una serie', 'Jugar a videojuegos', 'Dormir'],
  },
  {
    id: 'udt_35',
    level: 'Fácil',
    levelNumber: 4,
    category: 'Colores',
    prompt: 'Di 3 cosas de color rojo',
    examples: ['Tomate', 'Fresa', 'Extintor', 'Sangre', 'Camión de bomberos', 'Manzana'],
  },
  {
    id: 'udt_36',
    level: 'Fácil',
    levelNumber: 4,
    category: 'Colores',
    prompt: 'Di 3 cosas de color azul',
    examples: ['Cielo', 'Mar', 'Pitufo', 'Vaqueros', 'Arándanos', 'Gafas de bucear'],
  },
  {
    id: 'udt_37',
    level: 'Fácil',
    levelNumber: 4,
    category: 'Formas',
    prompt: 'Di 3 cosas que sean redondas',
    examples: ['Pelota', 'Moneda', 'Rueda', 'Naranja', 'Reloj de pared', 'Plato', 'Luna llena'],
  },
  {
    id: 'udt_38',
    level: 'Fácil',
    levelNumber: 4,
    category: 'Tamaños',
    prompt: 'Di 3 cosas que sean grandes',
    examples: ['Elefante', 'Avión', 'Edificio / Rascacielos', 'Ballena', 'Montaña', 'Barco'],
  },
  {
    id: 'udt_39',
    level: 'Fácil',
    levelNumber: 4,
    category: 'Tamaños',
    prompt: 'Di 3 cosas que sean pequeñas',
    examples: ['Hormiga', 'Grano de arena', 'Lenteja', 'Botón', 'Tornillo', 'Mosquito'],
  },
  {
    id: 'udt_40',
    level: 'Fácil',
    levelNumber: 4,
    category: 'Sonidos',
    prompt: 'Di 3 cosas que hagan ruido',
    examples: ['Sirena de ambulancia', 'Taladro', 'Despertador', 'Motor de avión', 'Petardo', 'Bocina'],
  },

  // ============================================================================
  // RONDA 5 — FÁCIL/MEDIA
  // ============================================================================
  {
    id: 'udt_41',
    level: 'Fácil / Media',
    levelNumber: 5,
    category: 'Sentidos',
    prompt: 'Di 3 cosas que huelan bien',
    examples: ['Café recién hecho', 'Perfume', 'Pan caliente', 'Flores / Rosas', 'Césped mojado', 'Vainilla'],
  },
  {
    id: 'udt_42',
    level: 'Fácil / Media',
    levelNumber: 5,
    category: 'Sentidos',
    prompt: 'Di 3 cosas que huelan mal',
    examples: ['Basura', 'Pescado podrido', 'Pies / Calcetines sucios', 'Cloaca / Alcantarilla', 'Gases / Pedos'],
  },
  {
    id: 'udt_43',
    level: 'Fácil / Media',
    levelNumber: 5,
    category: 'Temperatura',
    prompt: 'Di 3 cosas que estén calientes',
    examples: ['Café recién servido', 'Lava de volcán', 'Sopa hirviendo', 'Horno encendido', 'Fuego', 'Plancha'],
  },
  {
    id: 'udt_44',
    level: 'Fácil / Media',
    levelNumber: 5,
    category: 'Temperatura',
    prompt: 'Di 3 cosas que estén frías',
    examples: ['Hielo', 'Nieve', 'Helado', 'Cerveza fría', 'Congelador', 'Polo de limón'],
  },
  {
    id: 'udt_45',
    level: 'Fácil / Media',
    levelNumber: 5,
    category: 'Acciones',
    prompt: 'Di 3 cosas que puedas romper',
    examples: ['Vaso de cristal', 'Huevo', 'Papel', 'Plato', 'Rama', 'Corazón'],
  },
  {
    id: 'udt_46',
    level: 'Fácil / Media',
    levelNumber: 5,
    category: 'Día a Día',
    prompt: 'Di 3 cosas que puedas perder',
    examples: ['Llaves', 'Móvil', 'Cartera', 'Paciencia', 'Tiempo', 'Mechero', 'Paraguas'],
  },
  {
    id: 'udt_47',
    level: 'Fácil / Media',
    levelNumber: 5,
    category: 'Acciones',
    prompt: 'Di 3 cosas que puedas abrir',
    examples: ['Puerta', 'Ventana', 'Lata', 'Botella', 'Caja', 'Boca', 'Ojos'],
  },
  {
    id: 'udt_48',
    level: 'Fácil / Media',
    levelNumber: 5,
    category: 'Acciones',
    prompt: 'Di 3 cosas que puedas cerrar',
    examples: ['Puerta', 'Ventana', 'Cremallera', 'Libro', 'Ojos', 'Cuenta bancaria', 'Grifo'],
  },
  {
    id: 'udt_49',
    level: 'Fácil / Media',
    levelNumber: 5,
    category: 'Acciones',
    prompt: 'Di 3 cosas que puedas cortar',
    examples: ['Papel', 'Pelo', 'Uñas', 'Carne / Pan', 'Cuerda', 'Césped'],
  },
  {
    id: 'udt_50',
    level: 'Fácil / Media',
    levelNumber: 5,
    category: 'Acciones',
    prompt: 'Di 3 cosas que puedas esconder',
    examples: ['Dinero', 'Regalo sorpresa', 'Diario secreto', 'Llaves', 'Chuleta de examen'],
  },

  // ============================================================================
  // RONDA 6 — MEDIA
  // ============================================================================
  {
    id: 'udt_51',
    level: 'Media',
    levelNumber: 6,
    category: 'Improvisación',
    prompt: 'Di 3 excusas para llegar tarde',
    examples: ['Había mucho tráfico', 'No me sonó la alarma', 'Perdí el autobús / metro', 'No encontraba las llaves', 'Tuve una urgencia'],
  },
  {
    id: 'udt_52',
    level: 'Media',
    levelNumber: 6,
    category: 'Social',
    prompt: 'Di 3 cosas que nunca llevarías a una boda',
    examples: ['Vestido blanco (si no eres la novia)', 'Chándal', 'Chanclas', 'Bañador', 'Pijama', 'Pantalón corto'],
  },
  {
    id: 'udt_53',
    level: 'Media',
    levelNumber: 6,
    category: 'Supervivencia',
    prompt: 'Di 3 cosas que llevarías a una isla desierta',
    examples: ['Cuchillo / Machete', 'Mechero / Pedernal', 'Cantimplora / Filtro de agua', 'Cuerda', 'Mosquitera', 'Libro'],
  },
  {
    id: 'udt_54',
    level: 'Media',
    levelNumber: 6,
    category: 'Viajes',
    prompt: 'Di 3 cosas que llevarías de viaje',
    examples: ['Pasaporte / DNI', 'Cargador de móvil', 'Ropa interior', 'Cepillo de dientes', 'Dinero / Tarjetas', 'Maleta'],
  },
  {
    id: 'udt_55',
    level: 'Media',
    levelNumber: 6,
    category: 'Ocio',
    prompt: 'Di 3 cosas que harías en un día libre',
    examples: ['Dormir hasta tarde', 'Ver una peli / serie', 'Quedar con amigos a tomar algo', 'Pasear', 'Cocinar rico', 'Ir de compras'],
  },
  {
    id: 'udt_56',
    level: 'Media',
    levelNumber: 6,
    category: 'Humor',
    prompt: 'Di 3 cosas que te hacen reír',
    examples: ['Un chiste bueno', 'Un meme gracioso', 'Ver a un amigo tropezarse', 'Un monólogo de comedia', 'Hacer cosquillas'],
  },
  {
    id: 'udt_57',
    level: 'Media',
    levelNumber: 6,
    category: 'Emociones',
    prompt: 'Di 3 cosas que dan miedo',
    examples: ['Fantasmas / Espíritus', 'Oscuridad total', 'Películas de terror', 'Arañas gigantes', 'Quedarse encerrado', 'Hacienda'],
  },
  {
    id: 'udt_58',
    level: 'Media',
    levelNumber: 6,
    category: 'Situaciones',
    prompt: 'Di 3 cosas que dan vergüenza',
    examples: ['Caerse en público', 'Saludar a alguien que no te saludaba a ti', 'Llevar comida entre los dientes', 'Olvidar el nombre de alguien', 'Cantar en un karaoke sobrio'],
  },
  {
    id: 'udt_59',
    level: 'Media',
    levelNumber: 6,
    category: 'Social',
    prompt: 'Di 3 razones para cancelar un plan',
    examples: ['Estar enfermo / con fiebre', 'Estar reventado de cansancio', 'Pereza máxima', 'No tener dinero', 'Tener que trabajar / estudiar'],
  },
  {
    id: 'udt_60',
    level: 'Media',
    levelNumber: 6,
    category: 'Personal',
    prompt: 'Di 3 cosas que nunca prestarías',
    examples: ['Cepillo de dientes', 'Ropa interior', 'Contraseña del banco', 'Móvil desbloqueado', 'Pareja'],
  },

  // ============================================================================
  // RONDA 7 — MEDIA
  // ============================================================================
  {
    id: 'udt_61',
    level: 'Media',
    levelNumber: 7,
    category: 'Fantasía',
    prompt: 'Di 3 cosas que harías si fueras invisible',
    examples: ['Colarme en conciertos / cines gratis', 'Gastar bromas y mover cosas', 'Espiar conversaciones secretas', 'Entrar en el vestuario de mi equipo', 'Viajar en primera clase gratis'],
  },
  {
    id: 'udt_62',
    level: 'Media',
    levelNumber: 7,
    category: 'Deseos',
    prompt: 'Di 3 cosas que comprarías si fueras millonario',
    examples: ['Mansión con piscina', 'Superdeportivo / Ferrari', 'Yate de lujo', 'Isla privada', 'Jet privado', 'Un piso para mis padres'],
  },
  {
    id: 'udt_63',
    level: 'Media',
    levelNumber: 7,
    category: 'Superpoderes',
    prompt: 'Di 3 cosas que harías si pudieras teletransportarte',
    examples: ['Viajar a Japón a comer sushi', 'Ir a Hawai a la playa', 'Evitar atascos y transporte público', 'Despertarme 1 minuto antes de trabajar', 'Visitar las 7 maravillas'],
  },
  {
    id: 'udt_64',
    level: 'Media',
    levelNumber: 7,
    category: 'Superpoderes',
    prompt: 'Di 3 cosas que harías si pudieras parar el tiempo',
    examples: ['Dormir todas las horas que quiera', 'Copiar en un examen', 'Evitar accidentes', 'Caminar por la calle vacía', 'Pensar la respuesta perfecta'],
  },
  {
    id: 'udt_65',
    level: 'Media',
    levelNumber: 7,
    category: 'Ciencia Ficción',
    prompt: 'Di 3 cosas que preguntarías a un extraterrestre',
    examples: ['¿Venís en son de paz?', '¿Cómo funciona vuestra nave?', '¿Hay más civilizaciones en la galaxia?', '¿Coméis comida humana?', '¿Cómo lograsteis viajar tan rápido?'],
  },
  {
    id: 'udt_66',
    level: 'Media',
    levelNumber: 7,
    category: 'Aventura',
    prompt: 'Di 3 cosas que llevarías al espacio',
    examples: ['Cámara de fotos', 'Traje de astronauta', 'Música / Auriculares', 'Comida deshidratada favorita', 'Foto de mi familia'],
  },
  {
    id: 'udt_67',
    level: 'Media',
    levelNumber: 7,
    category: 'Terror Cotidiano',
    prompt: 'Di 3 cosas que NO quieres encontrar debajo de tu cama',
    examples: ['Monstruo / Persona escondida', 'Cucaracha / Rata', 'Payaso diabólico', 'Comida podrida de hace meses', 'Bicho venenoso'],
  },
  {
    id: 'udt_68',
    level: 'Media',
    levelNumber: 7,
    category: 'Humor',
    prompt: 'Di 3 nombres horribles para un perro',
    examples: ['Gato', 'Caca', 'Pulga', 'Comida', 'Señor Notario', 'Error', 'Mordisco'],
  },
  {
    id: 'udt_69',
    level: 'Media',
    levelNumber: 7,
    category: 'Cocina Absurda',
    prompt: 'Di 3 cosas que nunca meterías en una sopa',
    examples: ['Chocolate / Nutella', 'Zumo de naranja', 'Detergente', 'Monedas', 'Helado de fresa', 'Calzoncillos'],
  },
  {
    id: 'udt_70',
    level: 'Media',
    levelNumber: 7,
    category: 'Hogar Insólito',
    prompt: 'Di 3 cosas que no deberían estar en un baño',
    examples: ['Tostadora conectada', 'Colchón de matrimonio', 'Moto aparcada', 'Microondas', 'Barbacoa', 'Ordenador de torre'],
  },

  // ============================================================================
  // RONDA 8 — MEDIA/DIFÍCIL
  // ============================================================================
  {
    id: 'udt_71',
    level: 'Media / Difícil',
    levelNumber: 8,
    category: 'Palabras & Animales',
    prompt: 'Di 3 animales que empiecen por M',
    examples: ['Mono', 'Mosca', 'Murciélago', 'Medusa', 'Marmota', 'Morsa', 'Mantis'],
  },
  {
    id: 'udt_72',
    level: 'Media / Difícil',
    levelNumber: 8,
    category: 'Nombres con Letra',
    prompt: 'Di 3 nombres que empiecen por A',
    examples: ['Alejandro', 'Antonio', 'Ana', 'Álvaro', 'Adrián', 'Alba', 'Alicia', 'Andrea'],
  },
  {
    id: 'udt_73',
    level: 'Media / Difícil',
    levelNumber: 8,
    category: 'Gastronomía con Letra',
    prompt: 'Di 3 comidas que empiecen por P',
    examples: ['Pizza', 'Paella', 'Pasta', 'Pollo asado', 'Pescado frito', 'Puré de patatas', 'Pisto'],
  },
  {
    id: 'udt_74',
    level: 'Media / Difícil',
    levelNumber: 8,
    category: 'Geografía Mundial',
    prompt: 'Di 3 países que no estén en Europa',
    examples: ['Japón', 'Brasil', 'Canadá', 'Australia', 'Egipto', 'Argentina', 'Marruecos'],
  },
  {
    id: 'udt_75',
    level: 'Media / Difícil',
    levelNumber: 8,
    category: 'Biología',
    prompt: 'Di 3 animales que no sean mamíferos',
    examples: ['Cocodrilo (Reptil)', 'Águila (Ave)', 'Tiburón (Pez)', 'Rana (Anfibio)', 'Pulpo (Molusco)', 'Serpiente'],
  },
  {
    id: 'udt_76',
    level: 'Media / Difícil',
    levelNumber: 8,
    category: 'Propiedades',
    prompt: 'Di 3 cosas que sean transparentes',
    examples: ['Cristal / Vidrio', 'Agua limpia', 'Aire', 'Plástico de film', 'Lente de gafas', 'Hielo claro'],
  },
  {
    id: 'udt_77',
    level: 'Media / Difícil',
    levelNumber: 8,
    category: 'Cuerpo Humano',
    prompt: 'Di 3 cosas que puedas hacer sin utilizar las manos',
    examples: ['Caminar / Correr', 'Cantar / Hablar', 'Pestañear / Guiñar', 'Chutar un balón', 'Silbar', 'Pensar'],
  },
  {
    id: 'udt_78',
    level: 'Media / Difícil',
    levelNumber: 8,
    category: 'Percepción',
    prompt: 'Di 3 cosas que puedas ver pero no tocar',
    examples: ['El arcoíris', 'El sol / las estrellas', 'Un reflejo en el espejo', 'Una sombra', 'El horizonte', 'El humo'],
  },
  {
    id: 'udt_79',
    level: 'Media / Difícil',
    levelNumber: 8,
    category: 'Percepción',
    prompt: 'Di 3 cosas que puedas escuchar pero no ver',
    examples: ['El viento', 'Un eco', 'El latido del corazón', 'La música por auriculares', 'Tus propios pensamientos'],
  },
  {
    id: 'udt_80',
    level: 'Media / Difícil',
    levelNumber: 8,
    category: 'Pensamiento Lateral',
    prompt: 'Di 3 cosas que puedas perder sin haberlas tenido',
    examples: ['El tren / autobús', 'Una oportunidad', 'La cordura / cabeza', 'El tiempo', 'La paciencia', 'La dignidad'],
  },

  // ============================================================================
  // RONDA 9 — DIFÍCIL
  // ============================================================================
  {
    id: 'udt_81',
    level: 'Difícil',
    levelNumber: 9,
    category: 'Lengua & Retos',
    prompt: 'Di 3 palabras de 3 letras',
    examples: ['Sol', 'Pan', 'Mar', 'Pez', 'Luz', 'Voz', 'Gol', 'Gas', 'Dos', 'Sur'],
  },
  {
    id: 'udt_82',
    level: 'Difícil',
    levelNumber: 9,
    category: 'Juegos de Palabras',
    prompt: 'Di 3 palabras que empiecen y terminen con la misma letra',
    examples: ['Radar (R-R)', 'Ojo (O-O)', 'Amorosa (A-A)', 'Reír (R-R)', 'Oro (O-O)', 'Alas (A-A)', 'Sosos (S-S)'],
  },
  {
    id: 'udt_83',
    level: 'Difícil',
    levelNumber: 9,
    category: 'Geografía Mundial',
    prompt: 'Di 3 países que empiecen por C',
    examples: ['Canadá', 'Colombia', 'Chile', 'China', 'Croacia', 'Cuba', 'Costa Rica', 'Chipre'],
  },
  {
    id: 'udt_84',
    level: 'Difícil',
    levelNumber: 9,
    category: 'Reino Animal',
    prompt: 'Di 3 animales que tengan más de 4 patas',
    examples: ['Araña (8)', 'Hormiga (6)', 'Ciempiés (>4)', 'Cangrejo (10)', 'Abeja (6)', 'Pulpo (8 tentáculos)', 'Escarabajo (6)'],
  },
  {
    id: 'udt_85',
    level: 'Difícil',
    levelNumber: 9,
    category: 'Gastronomía',
    prompt: 'Di 3 cosas que puedas comer sin masticar',
    examples: ['Yogur', 'Sopa / Caldo', 'Gelatina', 'Natillas / Flan', 'Puré', 'Helado derretido'],
  },
  {
    id: 'udt_86',
    level: 'Difícil',
    levelNumber: 9,
    category: 'Pensamiento Lateral',
    prompt: 'Di 3 cosas que puedas beber pero que no sean bebidas',
    examples: ['Jarabe para la tos', 'Caldo de la sopa', 'Aceite de oliva', 'Agua de lluvia', 'Suero fisiológico'],
  },
  {
    id: 'udt_87',
    level: 'Difícil',
    levelNumber: 9,
    category: 'Límites Personales',
    prompt: 'Di 3 cosas que nunca harías delante de 1.000 personas',
    examples: ['Bailar en ropa interior', 'Llorar desconsoladamente', 'Hacer del vientre', 'Cantar a capela desafinando', 'Leer mi diario secreto'],
  },
  {
    id: 'udt_88',
    level: 'Difícil',
    levelNumber: 9,
    category: 'Dilemas Morales',
    prompt: 'Di 3 cosas que no harías por dinero',
    examples: ['Hacer daño a mi familia', 'Comer cacahuetes con cucarachas', 'Irme a la cárcel', 'Vender a mi mascota', 'Tatuarme la cara'],
  },
  {
    id: 'udt_89',
    level: 'Difícil',
    levelNumber: 9,
    category: 'Fama',
    prompt: 'Di 3 cosas que harías si mañana fueras famoso',
    examples: ['Salir a la calle con gafas de sol y gorra', 'Ir a La Revuelta / El Hormiguero', 'Firmar autógrafos', 'Alquilar un reservado VIP', 'Hacer una colaboración con Ibai'],
  },
  {
    id: 'udt_90',
    level: 'Difícil',
    levelNumber: 9,
    category: 'Utopías',
    prompt: 'Di 3 cosas que cambiarías del mundo',
    examples: ['Eliminar las guerras', 'Erradicar el hambre y la pobreza', 'Curar todas las enfermedades graves', 'Frenar el cambio climático', 'Semana laboral de 3 días'],
  },

  // ============================================================================
  // RONDA 10 — FINAL
  // ============================================================================
  {
    id: 'udt_91',
    level: 'Ronda Final',
    levelNumber: 10,
    category: 'Profesional & Absurdo',
    prompt: 'Di 3 cosas que NO llevarías a una entrevista de trabajo',
    examples: ['Cerveza abierta en la mano', 'Pijama de dinosaurio', 'Tu madre cogida del brazo', 'Una consola portátil', 'Un megáfono'],
  },
  {
    id: 'udt_92',
    level: 'Ronda Final',
    levelNumber: 10,
    category: 'Hogar & Desastres',
    prompt: 'Di 3 cosas que jamás meterías en una lavadora',
    examples: ['El móvil / portátil', 'Un gato / mascota', 'Zapatos con barro y piedras', 'Monedas sueltas', 'Una tostadora'],
  },
  {
    id: 'udt_93',
    level: 'Ronda Final',
    levelNumber: 10,
    category: 'Ciencia Ficción',
    prompt: 'Di 3 cosas que harían sospechar que eres un extraterrestre',
    examples: ['Tener la sangre verde', 'No parpadear nunca', 'Comer bombillas o metal', 'No saber qué es una pizza', 'Hablar en frecuencias ultra raras'],
  },
  {
    id: 'udt_94',
    level: 'Ronda Final',
    levelNumber: 10,
    category: 'Misterio & Acción',
    prompt: 'Di 3 cosas que harían sospechar que eres un espía',
    examples: ['Llevar 5 pasaportes con nombres distintos', 'Hablar por el pinganillo al reloj', 'Tener un maletín esposado a la muñeca', 'Usar gafas de sol de noche', 'Mirar por el retrovisor cada 3 segundos'],
  },
  {
    id: 'udt_95',
    level: 'Ronda Final',
    levelNumber: 10,
    category: 'Poderes Mentales',
    prompt: 'Di 3 cosas que harías si pudieras leer la mente',
    examples: ['Saber si le gusto a mi crush', 'Averiguar si alguien me está mintiendo', 'Ganar siempre al póquer', 'Saber qué piensa mi jefe de mí', 'Aprobar cualquier examen oral'],
  },
  {
    id: 'udt_96',
    level: 'Ronda Final',
    levelNumber: 10,
    category: 'Mundo Digital',
    prompt: 'Di 3 cosas que borrarías de internet',
    examples: ['Mis fotos de Tuenti / Facebook de 2010', 'Los bulos y fake news', 'Los virus informáticos', 'Los spoilers de series', 'El spam telefónico'],
  },
  {
    id: 'udt_97',
    level: 'Ronda Final',
    levelNumber: 10,
    category: 'Leyes Absurdas',
    prompt: 'Di 3 cosas que prohibirías durante un día',
    examples: ['Los teléfonos móviles', 'El dinero / cobrar por todo', 'Trabajar y madrugar', 'Poner alarmas', 'La negatividad y quejas'],
  },
  {
    id: 'udt_98',
    level: 'Ronda Final',
    levelNumber: 10,
    category: 'Nostalgia',
    prompt: 'Di 3 cosas que harías si pudieras volver a tener 10 años',
    examples: ['Comprar bitcoins', 'Jugar en el recreo sin preocupaciones', 'Abrazar a mis abuelos', 'No tener que pagar facturas', 'Ver dibujos comiendo nocilla'],
  },
  {
    id: 'udt_99',
    level: 'Ronda Final',
    levelNumber: 10,
    category: 'Tecnología Fantástica',
    prompt: 'Di 3 cosas que harías si tu móvil pudiera hablar',
    examples: ['Ponerle un esparadrapo en el micrófono', 'Pedirle que borre el historial de navegación', 'Sobornarlo para que no cuente mis secretos', 'Preguntarle qué hago con mi vida', 'Tirarlo por la ventana'],
  },
  {
    id: 'udt_100',
    level: 'Ronda Final',
    levelNumber: 10,
    category: '¡Reto Definitivo!',
    prompt: 'Di 3 cosas que nunca se te ocurrirían normalmente en menos de 5 segundos',
    examples: ['El nombre de un filósofo presocrático', '3 palabras en alemán', 'La capital de Burkina Faso', 'El cumpleaños de mi tío segundo', 'Cualquier cosa con la mente en blanco'],
  },
];
